import type { Anime } from './types';

// Mock anime data for previewing the design before the real Jikan integration.
// Image URLs point at MyAnimeList's CDN; if any go stale, the design's
// conditional rendering falls back to the surface background cleanly.

export const mockAiring: Anime[] = [
  {
    id: 52991,
    title: 'Frieren: Beyond Journey’s End',
    titleJp: '葬送のフリーレン',
    image: 'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg',
    score: 9.32,
    episodes: 28,
    type: 'TV',
    year: 2023,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    studios: ['Madhouse'],
  },
  {
    id: 44511,
    title: 'Chainsaw Man',
    titleJp: 'チェンソーマン',
    image: 'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg',
    score: 8.45,
    episodes: 12,
    type: 'TV',
    year: 2022,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Action', 'Supernatural'],
    studios: ['MAPPA'],
  },
  {
    id: 50265,
    title: 'Spy x Family',
    titleJp: 'SPY×FAMILY',
    image: 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',
    score: 8.45,
    episodes: 12,
    type: 'TV',
    year: 2022,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Comedy'],
    studios: ['Wit Studio', 'CloverWorks'],
  },
  {
    id: 40748,
    title: 'Jujutsu Kaisen',
    titleJp: '呪術廻戦',
    image: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
    score: 8.55,
    episodes: 24,
    type: 'TV',
    year: 2020,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Action', 'Supernatural'],
    studios: ['MAPPA'],
  },
  {
    id: 38000,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    titleJp: '鬼滅の刃',
    image: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
    score: 8.45,
    episodes: 26,
    type: 'TV',
    year: 2019,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Historical'],
    studios: ['ufotable'],
  },
  {
    id: 37521,
    title: 'Vinland Saga',
    titleJp: 'ヴィンランド・サガ',
    image: 'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg',
    score: 8.74,
    episodes: 24,
    type: 'TV',
    year: 2019,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Action', 'Adventure', 'Drama'],
    studios: ['Wit Studio'],
  },
  {
    id: 42310,
    title: 'Cyberpunk: Edgerunners',
    titleJp: 'サイバーパンク エッジランナーズ',
    image: 'https://cdn.myanimelist.net/images/anime/1818/126435l.jpg',
    score: 8.55,
    episodes: 10,
    type: 'ONA',
    year: 2022,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Action', 'Sci-Fi'],
    studios: ['Trigger'],
  },
  {
    id: 32182,
    title: 'Mob Psycho 100',
    titleJp: 'モブサイコ100',
    image: 'https://cdn.myanimelist.net/images/anime/8/80356l.jpg',
    score: 8.5,
    episodes: 12,
    type: 'TV',
    year: 2016,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Action', 'Comedy', 'Supernatural'],
    studios: ['Bones'],
  },
  {
    id: 16498,
    title: 'Attack on Titan',
    titleJp: '進撃の巨人',
    image: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
    score: 8.55,
    episodes: 25,
    type: 'TV',
    year: 2013,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Drama'],
    studios: ['Wit Studio'],
  },
  {
    id: 30276,
    title: 'One Punch Man',
    titleJp: 'ワンパンマン',
    image: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
    score: 8.5,
    episodes: 12,
    type: 'TV',
    year: 2015,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Action', 'Comedy'],
    studios: ['Madhouse'],
  },
  {
    id: 9253,
    title: 'Steins;Gate',
    titleJp: 'シュタインズ・ゲート',
    image: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg',
    score: 9.07,
    episodes: 24,
    type: 'TV',
    year: 2011,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Drama', 'Sci-Fi', 'Suspense'],
    studios: ['White Fox'],
  },
  {
    id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    titleJp: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    image: 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',
    score: 9.1,
    episodes: 64,
    type: 'TV',
    year: 2009,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Adventure', 'Drama'],
    studios: ['Bones'],
  },
];

export const mockSeasonal: Anime[] = [
  {
    id: 34599,
    title: 'Made in Abyss',
    titleJp: 'メイドインアビス',
    image: 'https://cdn.myanimelist.net/images/anime/6/86733l.jpg',
    score: 8.71,
    episodes: 13,
    type: 'TV',
    year: 2017,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    studios: ['Kinema Citrus'],
  },
  {
    id: 11061,
    title: 'Hunter x Hunter (2011)',
    titleJp: 'ハンター×ハンター',
    image: 'https://cdn.myanimelist.net/images/anime/11/33657l.jpg',
    score: 9.04,
    episodes: 148,
    type: 'TV',
    year: 2011,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Action', 'Adventure', 'Fantasy'],
    studios: ['Madhouse'],
  },
  {
    id: 31240,
    title: 'Re:Zero − Starting Life in Another World',
    titleJp: 'Re:ゼロから始める異世界生活',
    image: 'https://cdn.myanimelist.net/images/anime/11/79410l.jpg',
    score: 8.25,
    episodes: 25,
    type: 'TV',
    year: 2016,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Drama', 'Fantasy', 'Suspense'],
    studios: ['White Fox'],
  },
  {
    id: 1,
    title: 'Cowboy Bebop',
    titleJp: 'カウボーイビバップ',
    image: 'https://cdn.myanimelist.net/images/anime/4/19644l.jpg',
    score: 8.75,
    episodes: 26,
    type: 'TV',
    year: 1998,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Award Winning', 'Sci-Fi'],
    studios: ['Sunrise'],
  },
  {
    id: 31964,
    title: 'My Hero Academia',
    titleJp: '僕のヒーローアカデミア',
    image: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',
    score: 7.85,
    episodes: 13,
    type: 'TV',
    year: 2016,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action'],
    studios: ['Bones'],
  },
  {
    id: 21,
    title: 'One Piece',
    titleJp: 'ワンピース',
    image: 'https://cdn.myanimelist.net/images/anime/6/73245l.jpg',
    score: 8.7,
    episodes: null,
    type: 'TV',
    year: 1999,
    season: 'fall',
    status: 'Currently Airing',
    genres: ['Action', 'Adventure', 'Fantasy'],
    studios: ['Toei Animation'],
  },
  {
    id: 21459,
    title: 'Tokyo Ghoul',
    titleJp: '東京喰種',
    image: 'https://cdn.myanimelist.net/images/anime/5/64449l.jpg',
    score: 7.78,
    episodes: 12,
    type: 'TV',
    year: 2014,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Action', 'Horror'],
    studios: ['Pierrot'],
  },
  {
    id: 28977,
    title: 'Gintama°',
    titleJp: '銀魂°',
    image: 'https://cdn.myanimelist.net/images/anime/3/72078l.jpg',
    score: 9.06,
    episodes: 51,
    type: 'TV',
    year: 2015,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    studios: ['Bandai Namco Pictures'],
  },
  {
    id: 19,
    title: 'Monster',
    titleJp: 'モンスター',
    image: 'https://cdn.myanimelist.net/images/anime/10/18793l.jpg',
    score: 8.88,
    episodes: 74,
    type: 'TV',
    year: 2004,
    season: 'spring',
    status: 'Finished Airing',
    genres: ['Drama', 'Mystery', 'Suspense'],
    studios: ['Madhouse'],
  },
  {
    id: 35180,
    title: '3-gatsu no Lion 2nd Season',
    titleJp: '3月のライオン 第2シリーズ',
    image: 'https://cdn.myanimelist.net/images/anime/3/88469l.jpg',
    score: 9.0,
    episodes: 22,
    type: 'TV',
    year: 2017,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Drama', 'Slice of Life'],
    studios: ['Shaft'],
  },
  {
    id: 23273,
    title: 'Your Lie in April',
    titleJp: '四月は君の嘘',
    image: 'https://cdn.myanimelist.net/images/anime/3/67177l.jpg',
    score: 8.59,
    episodes: 22,
    type: 'TV',
    year: 2014,
    season: 'fall',
    status: 'Finished Airing',
    genres: ['Drama', 'Romance'],
    studios: ['A-1 Pictures'],
  },
  {
    id: 11757,
    title: 'Sword Art Online',
    titleJp: 'ソードアート・オンライン',
    image: 'https://cdn.myanimelist.net/images/anime/11/39717l.jpg',
    score: 7.2,
    episodes: 25,
    type: 'TV',
    year: 2012,
    season: 'summer',
    status: 'Finished Airing',
    genres: ['Action', 'Adventure', 'Fantasy'],
    studios: ['A-1 Pictures'],
  },
];

export const mockSearchResults: Anime[] = mockAiring.slice(0, 6);
